version: '3'
services:
  brp:
    container_name: brptool
    build:
      context: .
    volumes:
      - "./:/app"
    ports:
      - "3339:3000"
    working_dir: /app
    restart: always
    command: "node /app/app.js"
